version: '2'
services:
    marmotte-app:
        image: marmotte
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://marmotte-mysql:3306/marmotte?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    marmotte-mysql:
        extends:
            file: mysql.yml
            service: marmotte-mysql
